### ISSUE TITLE
Error com.xa.xpensauditor:drawable/prof_pic not found

### ISSUE THREAD

**Issue by sunandiniM1509** [SaiPavanYalla/ExpenseTracker#6]
![image](https://user-images.githubusercontent.com/47917036/193716453-b169063b-347e-4e2d-bc41-b7263c872915.png)

please do the needful!!

**Comment by SahithiAmmana** [comment]
Updated in the commit ccef8226b3099180453c45c4b1a6766ece294978

**Comment by SaiPavanYalla** [comment]
Great! works now.
