### ISSUE TITLE
Missing resource "dimen/row_padding_vertical" and few others

### ISSUE THREAD

**Issue by sunandiniM1509** [SaiPavanYalla/ExpenseTracker#7]
![image](https://user-images.githubusercontent.com/47917036/193717778-1c4ba731-1d0a-4c39-a8ce-cc4f4108751b.png)

Please do the needful

**Comment by mithila-reddy** [comment]
Updated in this commit a3f15c1f583189157ad96775ce10480a948a00e2

**Comment by SaiPavanYalla** [comment]
Works now, thanks!
